version: '3.5'

services:
  postgres:
    image: postgres:12.2
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wb
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5441:5432/tcp
